# SonarQube Project Configuration
sonar.projectKey=vensipokiya/AI-Based-Skin-Disease-Detection-System
sonar.projectName=AI-Based-Skin-Disease-Detection-System
sonar.language=py
sonar.sourceEncoding=UTF-8

# Source folders
sonar.sources=.

# Exclusions to solve duplications and false-positive code smells
# We exclude orphaned/legacy folders that contain identical logic to backend/app/
sonar.exclusions=routes/**, backend/api/**, **/migrations/**, **/test/**, **/staticfiles/**, **/node_modules/**

# Python specific
sonar.python.version=3
sonar.python.xunit.reportPath=reports/nosetests.xml

# CSS/HTML
sonar.css.exclusions=**/all.min.css
